# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZYStudyDemon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # Pods for ZYStudyDemon
  use_frameworks!
  
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 4.4.2'
  

  target 'ZYStudyDemonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZYStudyDemonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
